### ISSUE TITLE
Implement Worley noise

### ISSUE THREAD

**Issue by Razaekel** [brendanzab/noise-rs#138]
Voronoi noise is a subset of Worley noise, so maybe implement Voronoi for now, and mark Worley for later implementation.

[Worley Noise](https://en.wikipedia.org/wiki/Worley_noise)

**Comment by brendanzab** [comment]
Sounds good!

**Comment by amaranth** [comment]
I'm confused, the cell.rs file is already an implementation of (modified) Worley/cell noise.

**Comment by Razaekel** [comment]
Yes it is, @amaranth, but it needs to be adapted to the composable modules format that I've been working on.

**Comment by brendanzab** [comment]
@amaranth Are you on top of the new API? Curious as to your thoughts.

**Comment by amaranth** [comment]
No, unfortunately I haven't had a chance to look too closely at it. Based on the little I have checked it out it seems like a much better thought out version of the API was going to be working toward in my own noise code before starting to work on noise-rs instead so I'm pretty happy with it. I was just worried you were going to put a bunch of work in to reimplementing a noise primitive we already poured so much effort in to due to a misunderstanding from the naming.

On an unrelated note, it might be worth porting the surflet design of the perlin code to your value noise implementation and benchmarking it. I suspect it might be slightly slower or similar on 2D but faster for 3D and 4D. I'm just not sure what it'd do to the quality of the output.
