### ISSUE TITLE
Alternative to using PermutationTable?

### ISSUE THREAD

**Issue by jeffparsons** [brendanzab/noise-rs#151]
Hi there!

I notice that [PermutationTable is going to become private](https://docs.rs/noise/0.4.0/noise/struct.PermutationTable.html) so I shouldn't use it anymore, but it doesn't mention what I _should_ do instead. E.g. is the `PermutationTable` now automatically cached in, e.g., `Fbm`, or is there some other thing I should persist for efficiency if I want to sample many points of noise?

Thanks!

**Comment by Razaekel** [comment]
Jeff, thank you for the question! You bring up a very good point that I
should cover to reduce confusion about what happens.

Going forward, PermutationTable will be internally cached in each struct
that makes use of it, such as Perlin or Worley. This is due to there being
no need to access PermutationTable outside of the library. If you have a
good use case for PermutationTable outside of the library, let me know and
I'll reconsider making it private, or see if there's something else I can
do to enable that use case.

Fbm itself internally uses Perlin, FYI. I'm exploring how to enable the use
of alternative noise sources in the multifractal modules like Fbm or
Billow. I'm open to suggestions.

I'll try and expand the deprecation message to provide alternatives.

**Comment by jeffparsons** [comment]
Thanks for the advice, Nick. :)

My original commit upgrading my project to noise 0.4.0 is https://github.com/jeffparsons/planetkit/commit/9c8d3e2598d4a3438aca10e45e161cadc9da55d4 and the commit where I fix my abuse of it is https://github.com/jeffparsons/planetkit/commit/15413f813c12e8dffda2c38d90073075588763da.

I think it would be more than adequate to extend the deprecation note from

> will be made private by 1.0

to

> will be made private by 1.0; noise generator structs (e.g. Perlin) now store permutation table internally, so if you were storing PermutationTable for performance reasons, store the noise generator object instead.

Or something like that. :)

**Comment by jeffparsons** [comment]
(If you're ok with that suggestion, I can make a PR?)

**Comment by Razaekel** [comment]
That would be great!
